credentials_path: credentials.json
storage_bucket: 
sheets:
  - sheet_number: '0'
    sheet_name: 'None'
    sheet_url: 'None'
    # Start project from here
  - sheet_number: '1'
    sheet_name: 'Biblemind_RD'
    sheet_url: 'https://docs.google.com/spreadsheets/d/1zR4zKP_QbU4waH7LVQHHEbMG_Dn-SR4kz0oywpKsLyU/edit?usp=sharing'